name: Homepage
version: "1.1.1"
slug: homepage
description: "A modern, fully static, fast, secure fully proxied, highly customizable application dashboard"
arch:
  - amd64
  - aarch64
map: 
  - addon_config:rw
environment:
  HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev,192.168.254.135
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Web interface port, default is 3000."
url: "https://github.com/mwalbyte/haosaddonmw/tree/main/homepage"
panel_icon: "mdi:broadcast"
webui: "[PROTO:ssl]://[HOST]:[PORT:3000]"
